### ISSUE TITLE
How to use lyrebird? 

### ISSUE THREAD

**Issue by OrionRandD** [lyrebird-voice-changer/lyrebird-deb#1]
Could you add some examples on how to use it?
Or point to a link showing this? Thx

**Comment by ghost** [comment]
Hey Orion, this is the developer repo for creating .deb packages. The main [Lyrebird repo](https://github.com/lyrebird-voice-changer/lyrebird) can be found here. Scroll down a little to find [install instructions](https://github.com/lyrebird-voice-changer/lyrebird#install) and [usage instructions](https://github.com/lyrebird-voice-changer/lyrebird#lyrebird-usage).

**Comment by OrionRandD** [comment]
Thx4the info
